dependencies {
    compileOnly project(":core")
    compileOnly("org.incendo:cloud-paper:2.0.0-beta.16")
    compileOnly("net.milkbowl.vault:VaultAPI:1.7")
}

jar {
    archiveFileName = "MagicSpellsShop.jar"
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
