plugins {
    id("com.gradleup.shadow") version "9.4.1"
    id("antlr")
}

dependencies {
    implementation("org.apache.commons:commons-math4-core:4.0-beta1")
    implementation("com.github.ben-manes.caffeine:caffeine:3.2.2")
    implementation("com.github.Chronoken:EffectLib:1da888c")
    implementation("org.incendo:cloud-paper:2.0.0-beta.16")
    implementation("org.incendo:cloud-minecraft-extras:2.0.0-beta.16")
    implementation("org.incendo:cloud-processors-requirements:1.0.0-rc.1")
    implementation("org.bstats:bstats-bukkit:3.2.1")
    implementation("com.github.ezylang:EvalEx:3.6.2")

    implementation("org.antlr:antlr4-runtime:4.13.2")
    antlr("org.antlr:antlr4:4.13.2")

    implementation(project(path: ":nms:shared"))
    implementation(project(path: ":nms:latest"))
    implementation(project(path: ":nms:v26_1_2"))

    compileOnly("com.github.retrooper:packetevents-spigot:2.11.2")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
    compileOnly("me.libraryaddict.disguises:libsdisguises:11.0.16-SNAPSHOT")
    compileOnly("net.milkbowl.vault:VaultAPI:1.7")
    compileOnly("me.clip:placeholderapi:2.12.2")
    compileOnly("com.github.GriefPrevention:GriefPrevention:18.0.0")
    compileOnly("com.sk89q.worldguard:worldguard-core:7.1.0-SNAPSHOT")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.1.0-SNAPSHOT")
    compileOnly("com.sk89q.worldedit:worldedit-core:7.4.0-SNAPSHOT")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.4.0-SNAPSHOT")
}

/*
 * Undo extendsFrom relationship between the 'antlr' configuration and the 'api' configuration,
 * causing Shadow to shade it. See:
 * https://github.com/gradle/gradle/blob/fe863b559778fb57e926f55c2162bd17f153c637/platforms/jvm/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java#L70
 *
 * Workaround by: https://github.com/gradle/gradle/issues/820#issuecomment-3491381422
 */
configurations {
    api {
        extendsFrom = extendsFrom.findAll { it != configurations.antlr }
    }
}

base {
    archivesName = "MagicSpells"
}

shadowJar {
    relocate("com.github.benmanes.caffeine", "com.nisovin.magicspells.shaded.com.github.benmanes.caffeine")
    relocate("org.apache.commons.math4", "com.nisovin.magicspells.shaded.org.apache.commons.math4")
    relocate("de.slikey.effectlib", "com.nisovin.magicspells.shaded.effectlib")
    relocate("org.incendo.cloud", "com.nisovin.magicspells.shaded.cloud")
    relocate("io.leangen.geantyref", "com.nisovin.magicspells.shaded.geantyref")
    relocate("xyz.jpenilla.reflectionremapper", "com.nisovin.magicspells.shaded.reflectionremapper")
    relocate("net.fabricmc.mappingio", "com.nisovin.magicspells.shaded.mappingio")
    relocate("org.bstats", "com.nisovin.magicspells.shaded.bstats")
    relocate("de.slikey.exp4j", "com.nisovin.magicspells.shaded.exp4j")
    relocate("com.ezylang.evalex", "com.nisovin.magicspells.shaded.evalex")

    // Included by apache/commons-math, copied by this project.
    exclude("META-INF/LICENSE")
    exclude("META-INF/NOTICE")
    // Include our own copies of attributions.
    from("$rootDir/3rd_party_licenses") {
        into "META-INF/3rd_party_licenses"
    }
    from("$rootDir/NOTICE.md") {into "META-INF"}
    from("$rootDir/LICENSE") {into "META-INF"}

    archiveClassifier.set("")
}

jar {
    destinationDirectory = layout.buildDirectory.dir("publication")
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

generateGrammarSource {
    packageName = "com.nisovin.magicspells.util.grammars"
    arguments += ["-visitor", "-no-listener"]
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
