name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: $version
authors: [nisovin, TheComputerGeek2, Chronoken, tonythemacaroni, JasperLorelai]
website: "https://github.com/TheComputerGeek2/MagicSpells/"
api-version: "1.21.10"
softdepend:
    - GriefPrevention
    - Vault
    - ProtocolLib
    - WorldGuard
    - LibsDisguises
    - NoCheatPlus
    - PlaceholderAPI
    - XGlow
    - packetevents
